---
- name: update apt packages
  become: yes
  apt:
    update_cache: yes

- name: upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: create a user for Prometheus Node Exporter
  become: yes
  user:
    create_home: no
    name: node_exporter
    comment: NodeExporter User

- name: download node exporter binaries
  shell: |
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz

- name: install node exporter binaries
  become: yes
  shell: |
    cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: configure Prometheus Node Exporter to be available as a service
  become: yes
  template:
    src: "files/node-exporter.service"
    dest: "/etc/systemd/system/node-exporter.service"

- name: configure systemd
  become: yes
  shell: |
    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    systemctl status node-exporter
