# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: Node Exporter for exporting metrics to Prometheus - Abubakar
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      # Change this, as applicable to you
      KeyName: udacity
      # Change this, as applicable to you
      # You may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      ImageId: "ami-01f18be4e32df20e2"
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Prometheus Node Exporter
        - Key: Purpose
          Value: prometheus-node-exporter
        - Key: Project
          Value: udacity
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0
