---
- name: add user to run prometheus service
  become: yes
  shell: |
    useradd --no-create-home prometheus

- name: create a directory to host prometheus configuration
  become: yes
  shell: |
    mkdir /etc/prometheus

- name: create directory to host prometheus data
  become: yes
  shell: |
    mkdir /var/lib/prometheus

- name: download and extract prometheus files
  shell: |
    wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    tar xvfz prometheus-2.19.0.linux-amd64.tar.gz

- name: install prometheus
  become: yes
  shell: |
    cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin
    cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus
    cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus
    cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/

- name: cleanup
  shell: |
    rm -rf prometheus-2.19.0.linux-amd64.tar.gz prometheus-2.19.0.linux-amd64

- name: configure Prometheus to monitor itself
  become: yes
  template:
    src: "files/prometheus-self-monitor.yml"
    dest: "/etc/prometheus/prometheus.yml"

- name: configure Prometheus to be available as a service
  become: yes
  template:
    src: "files/prometheus-self-monitor.yml"
    dest: "/etc/systemd/system/prometheus.service"

- name: change the permissions of the directories, files and binaries we just added
  become: yes
  shell: |
    chown prometheus:prometheus /etc/prometheus
    chown prometheus:prometheus /usr/local/bin/prometheus
    chown prometheus:prometheus /usr/local/bin/promtool
    chown -R prometheus:prometheus /etc/prometheus/consoles
    chown -R prometheus:prometheus /etc/prometheus/console_libraries
    chown -R prometheus:prometheus /var/lib/prometheus

- name: configure systemd
  become: yes
  shell: |
    systemctl daemon-reload
    systemctl enable prometheus
